<?php

/**
 * Implementation of hook_menu().
 */
function fc_ads_menu() {
  $items = array();

  $items['welcome.html'] = array(
    'title' => t('Welcome'),
    'page callback' => 'fc_ads_splash_page',
    'access arguments' => array('access content'),
  );

  $items['admin/build/ads'] = array(
    'title' => t('Fast Company Ads'),
    'access arguments' => array('administer ads'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fc_ads_admin_settings'),
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

/**
 * Implementation of hook_theme().
 */
function fc_ads_theme($existing, $type, $theme, $path) {
  return array(
    'splash' => array(
      'arguments' => array('tag' => null),
      'template' => 'splash',
      'path' => drupal_get_path('module', 'fc_ads') .'/templates',
    ),
    'splash_header' => array(
      'arguments' => array(),
    ),
  );
}

/**
 * Implementation of hook_perm().
 */
function fc_ads_perm() {
  return array('administer ads', 'skip splash');
}


function fc_ads_splash_page() {
  $machinename = variable_get('dart_splash', 0);

  if ($tag = dart_tag_load($machinename)) {
    print theme('splash', $tag);

    drupal_page_footer();

    exit;
  }

}

/**
 * Template preprocess function for dart tags.
 */
function template_preprocess_splash(&$variables) {
  $tag = $variables['tag'];

  $variables['attributes'] = array('class' => 'dart-tag dart-name-' . $tag->machinename);
  $variables['script_src'] = fc_ads_prepare_script_src($tag);

  if (isset($tag->mode) && $tag->mode == 'test') {
    $variables['show_script_tag']   = TRUE;
    $variables['show_noscript_tag'] = TRUE;
  }
  else {
    $variables['show_script_tag']   = !$tag->settings['options']['scriptless'];
    $variables['show_noscript_tag'] = variable_get('dart_noscript', 1);
  }
  $variables['static_tag']        = l(theme('image', $tag->noscript['src'], '', '', NULL, FALSE), $tag->noscript['href'], array('html' => TRUE));
  $variables['noscript_tag']      = $variables['show_noscript_tag'] ? '<noscript>' . $variables['static_tag'] . '</noscript>' : '';

  $variables['tag'] = $tag;
}


/**
 * Build data for the noscript tag.
 */
function fc_ads_prepare_script_src($tag) {
  static $tile = NULL;

  // Set an initial value for tile.
  $tile = is_null($tile) ? variable_get('dart_special_tile_init', '0') : $tile;

  // Add the special key|value pairs to the noscript tag.
  $special_key_vals = _dart_get_special_key_vals();
  if (isset($special_key_vals['tile'])) {
    $tile++;
  }
  if (isset($special_key_vals['ord'])) {
    $ord = $ord == 0 ? rand(1000000000, 9999999999) . '?' : $ord;
  }

  $dart_url = 'http://ad.doubleclick.net';

  // Begin building the src for the noscript tag.
  $src  =  $dart_url . ($tag->network_id != '' ? '/' . $tag->network_id : '') . '/adj/' . $tag->prefix . '.' . $tag->site . '/' . $tag->zone . ';pos=' . $tag->pos . ';sz=' . $tag->sz . ';';

  // Add global & tag-specific key|value pairs.
  foreach ($tag->key_vals as $key=>$vals) {
    foreach ($vals as $val) {
      // Only add key|value pairs that do not require javacript and are not
      // "special" key|value pairs.
      if (!$val['eval'] && !in_array($key, $special_key_vals)) {
        $src .= $key . '=' . $val['val'] . ';';
      }
    }
  }

  // Now add the "special" key|value pairs.
  $src .= $tile ? 'tile=' . $tile .';' : '';

  return $src;
}




function fc_ads_admin_settings() {
  $form = array();

  $options = array( 0 => 'Off' );



  $dart_tags = _fc_ads_dart_tags();
  foreach ( $dart_tags as $name => $tag ) {
    $options[$name] = $tag->name;
  }


$form['splash_fieldset'] = array(
'#type' => 'fieldset',
'#title' => t('Splash Ad'),
);

  $form['splash_fieldset']['dart_splash'] = array(
      '#title' => 'Splash Ad',
      '#type' => 'select',
      '#options' => $options,
      '#weight' => 1,
      '#default_value' => variable_get('dart_splash', 0),
  );


$freqcap = array(0 => 'Once a day', 1 => 'Twice a day');

  $form['splash_fieldset']['dart_freq'] = array(
      '#title' => 'Splash Frequency Cap',
      '#type' => 'radios',
      '#options' => $freqcap,
      '#default_value' =>variable_get('dart_freq',1),
      '#weight' => 2,
  );

   $form['splash_fieldset']['dart_freq_custom'] = array(
      '#title' => t('Custom Frequency(Every x hour)'),
      '#type' => 'textfield',
      '#default_value' =>variable_get('dart_freq_custom',1),
      '#weight' => 2,
      '#size' =>3,
  );



  // $form['dart_takeover'] = array(
  //     '#title' => 'Takeover Ad Unit',
  //     '#type' => 'select',
  //     '#options' => $options,
  //     '#weight' => 1,
  //     '#default_value' => variable_get('dart_takeover', 0),
  // );

  $form['dart_river_injection'] = array(
      '#title' => 'River Injection Ad Unit',
      '#type' => 'select',
      '#options' => $options,
      '#weight' => 3,
      '#default_value' => variable_get('dart_river_injection', 0),
  );

  return system_settings_form($form);
}

function _fc_ads_dart_tags() {
  $dart_tags = array();

  $result = db_query("SELECT * FROM {dart_tags}");
  while ( $tag = db_fetch_object($result) ) {
    $dart_tags[$tag->machinename] = $tag;
  }

  return $dart_tags;
}

function fc_ads_preprocess_page($variables) {
  if ( !variable_get('dart_splash', 0) || defined('MAINTENANCE_MODE') || user_access('skip splash') ) {
    $variables['splash'] = null;
  }
  else {
    $variables['splash'] = theme('splash_header');
  }
}

/**
 * Output the themed splash JavaScript at the top of the page.
 */
function theme_splash_header() {
  $js = '';

  $cookie = 'http://www.fastcompany.com/sites/all/modules/custom/fc_ads/js/jquery.cookie.js';
  $freq = variable_get('dart_freq_custom',1);

  if ( !isset($_GET['partner']) || (isset($_GET['partner']) && $_GET['partner'] == 'rss') ) {
    $js = <<<EOT
<script type="text/javascript" src="$cookie"></script>
<script type="text/javascript">
  if ( typeof($.cookie('fastcompany_splash')) == 'undefined' || $.cookie('fastcompany_splash') != 1 ) {
    $.cookie('fastcompany_splash', 1, {
      path : '/',
      expires : "$freq"
    });

    window.location.assign("/welcome.html?destination=" + encodeURI(window.location.href));
  }
</script>
EOT;

    if ($_GET['type'] == 'external') {
      $js = '';
    }

  }

  else if (isset($_GET['partner'])) {
    $js = <<<EOT
<script type="text/javascript" src="$cookie"></script>
<script type="text/javascript">
 $.cookie('fastcompany_splash', 1, {
    path : '/',
    expires : 1
  });
</script>
EOT;
  }

  return $js;
}

